"""Обновленная миграция

Revision ID: 1e0f71eaa5d4
Revises: 
Create Date: 2025-02-14 19:56:46.056803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0f71eaa5d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table('pereval_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_areas_id'), 'pereval_areas', ['id'], unique=False)
    op.create_table('spr_activities_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spr_activities_types_id'), 'spr_activities_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('fam', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('otc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pereval_added',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coord_id', sa.Integer(), nullable=True),
    sa.Column('beauty_title', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('other_titles', sa.String(), nullable=True),
    sa.Column('connect', sa.String(), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('winter_level', sa.String(), nullable=True),
    sa.Column('summer_level', sa.String(), nullable=True),
    sa.Column('autumn_level', sa.String(), nullable=True),
    sa.Column('spring_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_added_id'), 'pereval_added', ['id'], unique=False)
    op.create_table('pereval_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pereval_id', sa.Integer(), nullable=True),
    sa.Column('img_title', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pereval_id'], ['pereval_added.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_images_id'), 'pereval_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pereval_images_id'), table_name='pereval_images')
    op.drop_table('pereval_images')
    op.drop_index(op.f('ix_pereval_added_id'), table_name='pereval_added')
    op.drop_table('pereval_added')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spr_activities_types_id'), table_name='spr_activities_types')
    op.drop_table('spr_activities_types')
    op.drop_index(op.f('ix_pereval_areas_id'), table_name='pereval_areas')
    op.drop_table('pereval_areas')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
